server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${turtle.datasource.driver-class-name}
    url: jdbc:mysql://${turtle.datasource.host}:${turtle.datasource.port}/${turtle.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${turtle.datasource.username}
    password: ${turtle.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug